# -*- coding: us-ascii -*-
# k4_pyqrack_driver.py -- run a K4 block natively on Qrack.
#
# Generated by K4-qasm.py from manifest.json. Reads the manifest at runtime,
# so editing the manifest does not mean regenerating this driver.
#
# WHY NOT exp()
# =====================================================================
# Qrack exposes exp(b, ph, q), applying e^{i*ph*(P (x) P)} in one call,
# which is exactly a Kitaev bond and would beat the five-gate QASM
# decomposition. It is NOT used here: in the pyqrack build this was
# generated against, the C entry point declares its Pauli-basis
# argument as int* while the Python wrapper passes ulonglong*, so the
# call raises a ctypes TypeError, and forcing the correct array type by
# hand segfaults. Worth raising upstream; until then the decomposition
# below is what runs.
#
# CONVENTIONS, fixed here and matched gate for gate by the QASM
# =====================================================================
#   bond term      exp(-i*theta*P(x)P)
#   r(PauliZ, ph)  is RZ(ph): measured, it puts relative phase e^{i*ph}
#                  on |1>, so the bond needs 2*theta, as QASM's rz does
#   basis change   XX: h ... h        YY: adjs h ... h s        ZZ: none
#   out_ket        little-endian; qubit 0 is the low bit
#
# Validated against exp(-i*theta*P(x)P) at fidelity 1 for all three
# colours by K4-qasm.py at generation time.
#
#   python3 k4_pyqrack_driver.py --block 0 --theta 0.1 --steps 4

import argparse
import json
import os

from pyqrack import QrackSimulator, Pauli

MANIFEST = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                        "manifest.json")


def bond(sim, qi, qj, c, theta):
    """exp(-i*theta*P(x)P) for colour c in 0,1,2 = XX,YY,ZZ."""
    for t in (qi, qj):
        if c == 0:
            sim.h(t)
        elif c == 1:
            sim.adjs(t)
            sim.h(t)
    sim.mcx([qi], qj)
    sim.r(Pauli.PauliZ, 2.0 * theta, qj)
    sim.mcx([qi], qj)
    for t in (qi, qj):
        if c == 0:
            sim.h(t)
        elif c == 1:
            sim.h(t)
            sim.s(t)


def trotter_step(sim, bonds, theta):
    for qi, qj, c in bonds:
        bond(sim, qi, qj, c, theta)


def measure_flux(sim, loop, word, anc):
    """Hadamard test on the flux word; returns <W> in [-1, 1].

    QrackCircuit cannot measure, which is why this runs against a live
    QrackSimulator rather than a compiled circuit.
    """
    sim.h(anc)
    for q, p in zip(loop, word):
        (sim.mcx, sim.mcy, sim.mcz)["XYZ".index(p)]([anc], q)
    sim.h(anc)
    return 1.0 - 2.0 * sim.prob(anc)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--manifest", default=MANIFEST)
    ap.add_argument("--block", type=int, default=0)
    ap.add_argument("--theta", type=float, default=0.1)
    ap.add_argument("--steps", type=int, default=1)
    a = ap.parse_args()

    man = json.load(open(a.manifest))
    byi = {b["index"]: b for b in man["blocks"]}
    b = byi[a.block]
    nq = man["qubits_per_block"]
    bonds = b["canonical_bonds"]

    sim = QrackSimulator(nq + 1)
    for _ in range(a.steps):
        trotter_step(sim, bonds, a.theta)
    w = measure_flux(sim, b["canonical_loop"], b["canonical_word"], nq)

    print("block %d (type %d): %d qubits + 1 ancilla" % (
        a.block, b["type"], nq))
    print("  %d bonds, %d step(s) at theta=%g" % (
        len(bonds), a.steps, a.theta))
    print("  flux word %s" % b["canonical_word"])
    print("  <W> = %+.6f" % w)


if __name__ == "__main__":
    main()
